version: "3.3"

services:
  
  qix-engine:
    command: -S AcceptEULA=${ACCEPT_EULA} -S LicenseServiceUrl=http://licenses:9200 -S ValidateJsonWebTokens=2 -S JsonWebTokenSecret=${JWT_SECRET}
  
  licenses:
    # The Licenses service is responsible for unlocking the Qlik Associative Engine.
    image: qlikcore/licenses:1.0.5
    environment:
      - LICENSES_SERIAL_NBR
      - LICENSES_CONTROL_NBR
    deploy:
      placement:
        constraints: [node.role == manager]
