version: "3.1"

services:
  openresty:
    # This is our externally-facing gateway, exposing the configured
    # things for all end-users. It has the Analytics UI bundled into it.
    # See https://github.com/qlik-ea/qliktive-custom-analytics-openresty
    image: qlikea/qliktive-custom-analytics-openresty:master-152
    restart: always
    ports:
      - "443:443"
    # uncomment for HTTP access:
    #  - "80:80"
    environment:
      SESSION_COOKIE_NAME: custom-analytics
      # kibana is defined in docker-compose.logging.yml, this is just here to
      # satisfy openresty DNS resolve:
      KIBANA_HOST: 127.0.0.1
      KIBANA_PORT: 5601
      VISUALIZER_HOST: viz
      VISUALIZER_PORT: 8080
      QIX_SESSION_HOST: qix-session
      QIX_SESSION_PORT: 9455
      AUTH_HOST: auth
      AUTH_PORT: 3000
    deploy:
      placement:
        constraints: [node.role == manager]

  redis:
    # The redis database stores sessions. The openresty gateway uses it to look
    # up JWTs based on the session cookie, while the authentication service use
    # it to create/delete these entries.
    image: redis:3.0.7-alpine
    deploy:
      placement:
        constraints: [node.role == manager]

  auth:
    # A service handling authentication and JWT generation.
    image: qlikea/qliktive-authentication-service:0.0.1-70
    secrets:
      - github_client_id
      - github_client_secret
      - jwt_secret
      - cookie_signing
      - accounts_file
    environment:
      SESSION_COOKIE_NAME: custom-analytics
      GITHUB_CLIENT_ID_FILE: /run/secrets/github_client_id
      GITHUB_CLIENT_SECRET_FILE: /run/secrets/github_client_secret
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      COOKIE_SIGNING_FILE: /run/secrets/cookie_signing
      SUCCESS_REDIRECT_URL: /#/app
      FAILURE_REDIRECT_URL: /
      AUTH_STRATEGY: local #change to 'github' to login via github
      ACCOUNTS_FILE: /run/secrets/accounts_file
    deploy:
      placement:
        constraints: [node.role == manager]

  viz:
    # A swarm visualizer, enables us to view what the cluster
    # looks like, which services are running on which nodes etc.
    image: dockersamples/visualizer:latest
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]

  mira:
    # Mira is our QIX Engine Discovery Service. It provides internal
    # APIs to list (or query) all available QIX Engine containers
    # in the cluster.
    # See https://github.com/qlik-ea/mira
    image: qlikea/mira:0.0.1-143
    command: --mode=swarm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - QIX_ENGINE_IMAGE_NAME=qlikea/engine
    deploy:
      placement:
        constraints: [node.role == manager]

  qix-engine:
    # QIX Engine is configured to run on all worker nodes in the
    # cluster, and is the service we primarily want to scale up in
    # this use-case.
    image: qlikea/engine:12.26.0
    command: -S EnableTTL=1 -S SessionLogVerbosity=5
    volumes:
      - /home/docker/data/csv:/data
      - /home/docker/data/doc:/doc
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]

  qix-session:
    # This service handles preparation of sessions against
    # QIX Engines. Uses Mira to find appropriate containers
    # to place the session on.
    # See https://github.com/qlik-ea/qliktive-qix-session-service
    image: qlikea/qliktive-qix-session-service:0.0.1-26
    deploy:
      placement:
        constraints: [node.role == manager]

secrets:
  github_client_id:
    file: ./secrets/GITHUB_CLIENT_ID
  github_client_secret:
    file: ./secrets/GITHUB_CLIENT_SECRET
  jwt_secret:
    file: ./secrets/JWT_SECRET
  cookie_signing:
    file: ./secrets/COOKIE_SIGNING
  accounts_file:
    file: ./secrets/ACCOUNTS
