version: "3.3"

# This file is for development overrides (e.g. config for docker-compose up),
# not used when deploying to Swarm.

services:
  openresty:
    container_name: openresty

  auth:
    environment:
      GITHUB_CLIENT_ID_FILE: /secrets/GITHUB_CLIENT_ID
      GITHUB_CLIENT_SECRET_FILE: /secrets/GITHUB_CLIENT_SECRET
      JWT_SECRET_FILE: /secrets/JWT_SECRET
      COOKIE_SIGNING_FILE: /secrets/COOKIE_SIGNING
      ACCOUNTS_FILE: /secrets/accounts_file
    volumes:
      - secrets-volume:/secrets

  viz:
    # Not used here, but Docker does not support removing services in override

  qix-engine:
    container_name: qix-engine
    # Use named volume so that 'docker cp' can be used to move files from job space
    # into remote docker space on CCI.
    volumes:
      - data-volume:/data
      - doc-volume:/doc

  mira:
    # On CCI, run Mira in 'local' mode instead of default 'swarm' mode.
    command: --mode=local

  dummy-data:
    # Dummy container just to hold data that is needed in CCI remote docker space.
    # Not to be used in any production scenario.
    image: alpine:3.6
    container_name: dummy-data
    command: sleep 1m
    volumes:
      - data-volume:/data
      - doc-volume:/doc
      - secrets-volume:/secrets

volumes:
  data-volume:
  doc-volume:
  secrets-volume:
