version: "3.3"

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.7.0
    configs:
      - source: filebeat-config
        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/hostfs/var/lib/docker/containers:rw
    user: root
    deploy:
      mode: global

  elasticsearch:
    # This service only runs as one instance in our stack and is
    # used by Kibana (consuming) and Logstash (storing).
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.0
    environment:
      ES_JAVA_OPTS: "-Xmx1500m -Xms1500m"
    deploy:
      placement:
        constraints:
          - engine.labels.elk == true

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.7.0
    configs:
      - source: logstash-pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    environment:
      LOG_LEVEL: warn
      LOG_FORMAT: json
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    deploy:
      placement:
        constraints:
          - engine.labels.elk == true

  kibana:
    # Used for visualizing and viewing logs stored in elasticsearch.
    image:  docker.elastic.co/kibana/kibana-oss:6.7.0
    configs:
      - source: kibana-config
        target: /usr/share/kibana/config/kibana.yml
    deploy:
      placement:
        constraints:
          - engine.labels.elk == true

  openresty:
    environment:
      KIBANA_HOST: kibana

configs:
  filebeat-config:
    file: ./configs/filebeat/filebeat.yml
  logstash-pipeline:
    file: ./configs/logstash/logstash.conf
  kibana-config:
    file: ./configs/kibana/kibana.yml
