version: "3.1"

services:
  openresty:
    # This is our externally-facing gateway, exposing the configured
    # things for all end-users. It has the Analytics UI bundled into it.
    # See https://github.com/qlik-ea/qliktive-custom-analytics-openresty
    image: qlikea/qliktive-custom-analytics-openresty:secure-67
    secrets:
      - cert-gateway.crt
      - cert-gateway.key
    restart: always
    ports:
      - "443:443"
    # uncomment for HTTP access:
    #  - "80:80"
    environment:
      SESSION_COOKIE_NAME: custom-analytics
      KIBANA_HOST: kibana
      KIBANA_PORT: 5601
      VISUALIZER_HOST: viz
      VISUALIZER_PORT: 8080
      QIX_SESSION_HOST: qix-session
      QIX_SESSION_PORT: 9455
      AUTH_HOST: auth
      AUTH_PORT: 3000
      CERT_FILE: /run/secrets/cert-gateway.crt
      CERT_KEY: /run/secrets/cert-gateway.key
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    deploy:
      placement:
        constraints: [node.role == manager]

  redis:
    # The redis database stores sessions. The openresty gateway uses it to look
    # up JWTs based on the session cookie, while the authentication service use
    # it to create/delete these entries.
    image: redis:3.0.7-alpine
    deploy:
      placement:
        constraints: [node.role == manager]

  auth:
    # A service handling authentication and JWT generation.
    image: qlikea/qliktive-authentication-service:0.0.1-40
    secrets:
      - github_client_id
      - github_client_secret
      - jwt_secret
      - cookie_signing
    environment:
      SESSION_COOKIE_NAME: custom-analytics
      GITHUB_CLIENT_ID_FILE: /run/secrets/github_client_id
      GITHUB_CLIENT_SECRET_FILE: /run/secrets/github_client_secret
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      COOKIE_SIGNING_FILE: /run/secrets/cookie_signing
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    deploy:
      placement:
        constraints: [node.role == manager]

  elasticsearch:
    # This service only runs as one instance in our stack and is
    # used by Kibana (consuming) and Logstash (storing).
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    deploy:
      placement:
        constraints: [node.role == manager]

  logstash:
    # Logstash runs as one instance on each node in the cluster
    # since it's using the UDP protocol. Pushes all its collected
    # logs to the elasticsearch instance.
    # See https://github.com/qlik-ea/qliktive-custom-analytics-logstash
    image: qlikea/qliktive-custom-analytics-logstash:master-30
    ports:
      - "12201:12201/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    deploy:
      mode: global

  kibana:
    # Used for visualizing and viewing logs stored in elasticsearch.
    # See https://github.com/qlik-ea/qliktive-kibana-custom-analytics
    image: qlikea/qliktive-custom-analytics-kibana:master-3
    deploy:
      placement:
        constraints: [node.role == manager]

  viz:
    # A swarm visualizer, enables us to view what the cluster
    # looks like, which services are running on which nodes etc.
    image: dockersamples/visualizer:stable
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]

  mira:
    # Mira is our QIX Engine Discovery Service. It provides internal
    # APIs to list (or query) all available QIX Engine containers
    # in the cluster.
    # See https://github.com/qlik-ea/mira
    image: qlikea/mira:0.0.1-17
    command: --mode=swarm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - QIX_ENGINE_IMAGE_NAME=qlikea/engine
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    deploy:
      placement:
        constraints: [node.role == manager]

  qix-engine:
    # QIX Engine is configured to run on all worker nodes in the
    # cluster, and is the service we primarily want to scale up in
    # this use-case.
    image: qlikea/engine:12.21.0
    command: -S TrafficLogVerbosity=5 -S EnableTTL=1
    volumes:
      - /home/docker/data/csv:/data
      - /home/docker/data/doc:/doc
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]

  # This service handles preparation of sessions against
  # QIX Engines. Uses Mira to find appropriate containers
  # to place the session on.
  # See https://github.com/qlik-ea/qliktive-qix-session-service
  qix-session:
    image: qlikea/qliktive-qix-session-service:0.0.1-23
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    deploy:
      placement:
        constraints: [node.role == manager]

secrets:
  github_client_id:
    file: ./secrets/GITHUB_CLIENT_ID
  github_client_secret:
    file: ./secrets/GITHUB_CLIENT_SECRET
  jwt_secret:
    file: ./secrets/JWT_SECRET
  cookie_signing:
    file: ./secrets/COOKIE_SIGNING
  cert-gateway.crt:
    file: ./secrets/cert-gateway.crt
  cert-gateway.key:
    file: ./secrets/cert-gateway.key
