version: "3.3"

services:
  elasticsearch:
    # This service only runs as one instance in our stack and is
    # used by Kibana (consuming) and Logstash (storing).
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    deploy:
      placement:
        constraints: [node.role == manager]

  logstash:
    image: docker.elastic.co/logstash/logstash:5.2.2
    configs:
      - source: logstash-config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash-pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    ports:
      - "12201:12201/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    deploy:
      mode: global

  kibana:
    # Used for visualizing and viewing logs stored in elasticsearch.
    image:  docker.elastic.co/kibana/kibana:5.2.2
    configs:
      - source: kibana-config
        target: /usr/share/kibana/config/kibana.yml
    deploy:
      placement:
        constraints: [node.role == manager]

  openresty:
    environment:
      KIBANA_HOST: kibana
      KIBANA_PORT: 5601
    # logging:
    #   driver: "gelf"
    #   options:
    #     gelf-address: "udp://localhost:12201"

  auth:
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"

  mira:
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"

  qix-engine:
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"

  qix-session:
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"

configs:
  logstash-config:
    file: ./configs/logstash/logstash.yml
  logstash-pipeline:
    file: ./configs/logstash/logstash.conf
  kibana-config:
    file: ./configs/kibana/kibana.yml
