version: "3.1"

# This file is for development overrides (e.g. config for docker-compose up),
# not used when deploying to Swarm.

services:
  openresty:
    volumes:
      - /path/to/local/ui:/usr/local/openresty/nginx/html/dev
  viz:
    # Not used here, but Docker does not support removing services in override

  qix-engine:
    volumes:
      - ./data/csv:/data
      - ./data/doc:/doc

  mira:
    command: --mode=local
