version: "3.3"

services:
  openresty:
    secrets:
      - cert_file
      - cert_key
    environment:
      # CERT_FILE: /run/secrets/cert_file
      # CERT_KEY: /run/secrets/cert_key

secrets:
  cert_file:
    file: ./secrets/DEPLOY_SSL_CERT
  cert_key:
    file: ./secrets/DEPLOY_SSL_KEY
