version: 2
jobs:
  build:
    docker:
      - image: node:7
    working_directory: ~/qliktive-custom-analytics
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "test/package.json" }}
      - run:
          name: Install dependencies
          command: npm install --quiet
          working_directory: ~/qliktive-custom-analytics/test
      - run:
          name: Run ESLint
          command: npm run lint
          working_directory: ~/qliktive-custom-analytics/test
      - save_cache:
          key: dependency-cache-{{ checksum "test/package.json" }}
          paths:
            - test/node_modules
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Validate docker-compose files
          command: npm run validate:compose
          working_directory: ~/qliktive-custom-analytics/test
      - run:
          name: Install docker client
          command: |
            curl -L -o /tmp/docker-17.06.0-dev.tgz https://master.dockerproject.org/linux/x86_64/docker-17.06.0-dev.tgz
            tar -xz -C /tmp -f /tmp/docker-17.06.0-dev.tgz
            mv /tmp/docker/* /usr/bin
      - setup_remote_docker
      - run:
          name: Login to Dockerhub
          command: |
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - run:
          name: Deploy to remote Docker space
          command: |
            echo $GITHUB_CLIENT_ID > ~/qliktive-custom-analytics/secrets/GITHUB_CLIENT_ID
            echo $GITHUB_CLIENT_SECRET > ~/qliktive-custom-analytics/secrets/GITHUB_CLIENT_SECRET
            echo $JWT_SECRET > ~/qliktive-custom-analytics/secrets/JWT_SECRET
            echo $SLACK_WEBHOOK > ~/qliktive-custom-analytics/secrets/SLACK_WEBHOOK
            ./local.sh deploy
      - run:
          name: Wait for deployment to come up
          command: |
            CONTAINER_ID=$(docker ps -aqf "name=openresty")
            set +e
            RETRIES=0
            while [[ "$STATUS" != "running" && $RETRIES -le 30 ]]; do
              STATUS=$(docker inspect -f '{{.State.Status}}' "$CONTAINER_ID")
              echo -n "."
              sleep 1
              RETRIES=$[$RETRIES+1]
            done
            if [ "$STATUS" != "running" ]; then
              echo "Gateway (Openresty) did not reach running state."
              exit 1
            fi
      - run:
          name: Run E2E tests in remote Docker space
          command: ./run-e2e-tests-cci.sh
          working_directory: ~/qliktive-custom-analytics/scripts
      - deploy:
          name: Deploy public demo to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              curl -L https://github.com/docker/machine/releases/download/v0.12.2/docker-machine-`uname -s`-`uname -m` > /usr/local/bin/docker-machine
              chmod +x /usr/local/bin/docker-machine
              scp -o StrictHostKeyChecking=no ubuntu@${DOCKER_AWS_MANAGER_IP}:/home/ubuntu/qliktive-*.zip ~/
              apt-get update
              apt-get install unzip
              for i in ~/qliktive-*.zip; do ./import-machine.sh "$i"; done;
              export DOCKER_HOST="tcp://${DOCKER_AWS_MANAGER_IP}:2376"
              export DOCKER_CERT_PATH="/root/.docker/machine/machines/${DOCKER_AWS_MANAGER_NAME}"
              export DOCKER_MACHINE_NAME=${DOCKER_AWS_MANAGER_NAME}
              scp -o StrictHostKeyChecking=no ubuntu@${DOCKER_AWS_MANAGER_IP}:/home/ubuntu/DEPLOY_SSL_* ~/qliktive-custom-analytics/secrets/
              cd ..
              AUTH_STRATEGY="github" docker-compose -f docker-compose.yml -f docker-compose.pregen-ssl.yml config > docker-compose.merged.yml
              \cp docker-compose.merged.yml docker-compose.yml

              # Check if configs was changed. If so we need to remove stack before deploying to force an update.
              CONFIGS_CHANGED=$(git log --name-status HEAD~1..HEAD configs)

              if [[ -n $CONFIGS_CHANGED ]]; then
                echo "Configuration files was changed in the last commit. Removing and redeploying stack"
                SKIP_SWARM_ENV="true" DOCKER_PREFIX="qliktive-prod" DOCKER_DRIVER="amazonec2" ./swarm.sh clean
              fi

              SKIP_SWARM_ENV="true" DOCKER_PREFIX="qliktive-prod" DOCKER_DRIVER="amazonec2" ./swarm.sh deploy
              # wait a little bit to let the manager node breath:
              sleep 5
              # create the documentation site volume (deployed to the manager node from the qlik-ea/info CI):
              docker volume create -d local-persist -o mountpoint=/home/ubuntu/docs --name=docs-folder 2>&1
              docker service update --mount-add type=volume,source=docs-folder,target=/usr/local/openresty/nginx/html/docs custom-analytics_openresty
            fi
          working_directory: ~/qliktive-custom-analytics/scripts
