version: 2
jobs:
  build:
    docker:
      - image: node:7
    working_directory: ~/qliktive-custom-analytics
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --quiet
          working_directory: ~/qliktive-custom-analytics/test
      - run:
          name: Run ESLint
          command: npm run lint
          working_directory: ~/qliktive-custom-analytics/test
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Validate docker-compose files
          command: npm run validate:compose
          working_directory: ~/qliktive-custom-analytics/test
      - run:
          name: Install docker client
          command: |
            curl -L -o /tmp/docker-17.04.0-ce.tgz https://get.docker.com/builds/Linux/x86_64/docker-17.04.0-ce.tgz
            tar -xz -C /tmp -f /tmp/docker-17.04.0-ce.tgz
            mv /tmp/docker/* /usr/bin
      - setup_remote_docker
      - run:
          name: Run E2E tests on a local setup
          command: |
            echo "### Create certificates"
            ../scripts/create-certs.sh -a localhost

            docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"

            echo "### Starting secrets service"
            docker-compose -f ../docker-compose.yml -f ../docker-compose.cci.yml up -d secrets
            
            echo "### Copying secrets to dummy secrets container"
            docker cp ../secrets/cert-gateway.crt secrets:/secrets
            docker cp ../secrets/cert-gateway.key secrets:/secrets

            echo "### Starting full stack"
            docker-compose -f ../docker-compose.yml -f ../docker-compose.cci.yml up -d

            echo "### Copying data to engine container"
            docker cp ../data/csv/. qix-engine:/data
            docker cp ../data/doc/. qix-engine:/doc
    
            echo "### Find out IP address of gateway"
            CONTAINER_ID=$(docker ps -aqf "name=openresty")
            TEST_HOST=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.Gateway}}{{end}}' "$CONTAINER_ID")

            echo "### Build docker image for test"
            docker build --build-arg TEST_HOST="$TEST_HOST" -t test/test-e2e .

            echo "### Execute tests"
            docker run --rm test/test-e2e
          working_directory: ~/qliktive-custom-analytics/test
