version: 2
jobs:
  build:
    docker:
      - image: node:8
    working_directory: ~/qliktive-custom-analytics
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "test/package.json" }}
      - run:
          name: Install Dependencies - Test
          command: npm install --quiet
          working_directory: ~/qliktive-custom-analytics/test
      - run:
          name: Run ESLint
          command: npm run lint
          working_directory: ~/qliktive-custom-analytics/test
      - save_cache:
          key: dependency-cache-{{ checksum "test/package.json" }}
          paths:
            - test/node_modules