version: 2
jobs:
  build:
    docker:
      - image: node:7
    working_directory: ~/qliktive-custom-analytics
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "test/package.json" }}
      - run:
          name: Install dependencies
          command: npm install --quiet
          working_directory: ~/qliktive-custom-analytics/test
      - run:
          name: Run ESLint
          command: npm run lint
          working_directory: ~/qliktive-custom-analytics/test
      - save_cache:
          key: dependency-cache-{{ checksum "test/package.json" }}
          paths:
            - test/node_modules
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.14.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Validate docker-compose files
          command: npm run validate:compose
          working_directory: ~/qliktive-custom-analytics/test
      - setup_remote_docker
      - run:
          name: Login to Dockerhub
          command: |
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - run:
          name: Deploy to remote Docker space
          command: |
            ./deploy-local.sh
          working_directory: ~/qliktive-custom-analytics/scripts
      - run:
          name: Run E2E tests in remote Docker space
          command: ./run-e2e-tests-cci.sh
          working_directory: ~/qliktive-custom-analytics/scripts
      - deploy:
          name: Deploy public demo to AWS
          filters:
            branches:
              only: deployFromCCI
          command: |
              curl -L https://github.com/docker/machine/releases/download/v0.12.0/docker-machine-`uname -s`-`uname -m` > /usr/local/bin/docker-machine
              chmod +x /usr/local/bin/docker-machine
              scp -o StrictHostKeyChecking=no ubuntu@54.229.164.168:/home/ubuntu/*-docker-*.zip ~/
              apt-get update
              apt-get install unzip
              for i in ~/*-docker-*.zip; do ./import-machine.sh "$i"; done;
              ./deploy-stack.sh -u demo
          working_directory: ~/qliktive-custom-analytics/scripts
